[package]
name = "sqlite-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rusqlite]
version = "0.29.0"
features = ["bundled"]

[dependencies]
rand = "0.8.4"
rand_distr = "0.4.2"